version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    networks:
      - project

 


networks: 
  project:

